
name: Deploy to Arvan cloud

on:
  push:
    branches: [ "main" ]


jobs:
  test:
    name : test
    runs-on : ubuntu-latest
    steps:
    - name : see working directory
      run : pwd && ls -la
  
  
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name : prepare env
      run : cd /home/ubuntu/cidi/CI-CD-test-repo
    
    - name : git pull
      run : git pull
